kernel.o: src/kernel.c include/boot/multiboot.h include/types.h \
  include/boot/x86_desc.h include/lib.h include/types.h
lib.o: src/lib.c include/lib.h include/types.h
boot.o: src/boot/boot.S include/boot/multiboot.h include/boot/x86_desc.h \
  include/types.h
x86_desc.o: src/boot/x86_desc.S include/boot/x86_desc.h include/types.h
